version: '3.8'
services:
    postgres:
        image: postgres:15.0-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=task_manager
            - POSTGRES_USER=tm_admin
            - POSTGRES_PASSWORD=admin
            - PGDATA=/var/lib/postgresql/data/
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_mqtt_log.sql
            - ./pg_data_1:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
             postgres:
                aliases:
                    - postgres-test
        healthcheck:
            test: [ "CMD", "pg_isready", "--quiet", "--port=5432", "--dbname=task_manager", "--username=tm_admin" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s

    pgadmin:
        image: dpage/pgadmin4:7.2
        environment:
            PGADMIN_DEFAULT_EMAIL: "flages1325@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "asdfasdfsdf"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G
        networks:
            - postgres


    backend:
        build: .
        environment:
            APP_HOST: "${APP_HOST}"
            APP_PORT: "${APP_PORT}"
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT}"
            DB_NAME: "${DB_NAME}"
            DB_LOGIN: "${DB_LOGIN}"
            DB_PASSWORD: "${DB_PASSWORD}"
        networks:
            - postgres
        ports:
            - "4322:4322"
        depends_on:
            postgres:
                condition: service_healthy

networks:
    postgres:
volumes:
    db:
